services:
  config-server:
    build: ./ConfigServer
    container_name: config-server
    depends_on:
      - kafka
      - elasticsearch
      - logstash
      - kibana
      - zipkin
      - keycloak
    ports:
      - "8888:8888"
    networks:
      - microservices-net

  discovery-server:
    build: ./DiscoveryServer
    container_name: discovery-server
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    networks:
      - microservices-net

  gateway:
    build: ./Gateway
    container_name: gateway-service
    ports:
      - "8222:8222"
    depends_on:
      - config-server
      - discovery-server
    networks:
      - microservices-net
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_APPLICATION_NAME: GatewayService
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/micro-service/protocol/openid-connect/certs
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/micro-service
      SPRING_CLOUD_DISCOVERY_CLIENT_SIMPLE_HINTS.USER-SERVICE: "http://user-service:8001" # Gợi ý URL cho Gateway

  user-service:
    build: ./UserService
    container_name: user-service
    ports:
      - "8001:8001"
    depends_on:
      - config-server
      - discovery-server
    networks:
      - microservices-net
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_APPLICATION_NAME: UserService
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/micro-service/protocol/openid-connect/certs
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/micro-service
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true" # Sử dụng IP thay vì hostname
      EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS: 10
      EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS: 30

  product-service:
    build: ./ProductService
    container_name: product-service
    ports:
      - "8002:8002"
    depends_on:
      - config-server
      - discovery-server
    networks:
      - microservices-net
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_APPLICATION_NAME: ProductService
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/micro-service/protocol/openid-connect/certs
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/micro-service
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true" # Sử dụng IP thay vì hostname
      EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS: 10
      EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS: 30
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  order-service:
    build: ./OrderService
    container_name: order-service
    ports:
      - "8003:8003"
    depends_on:
      - config-server
      - discovery-server
    networks:
      - microservices-net
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_APPLICATION_NAME: OrderService
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/micro-service/protocol/openid-connect/certs
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/micro-service
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true" # Sử dụng IP thay vì hostname
      EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS: 10
      EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS: 30
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  payment-service:
    build: ./PaymentService
    container_name: payment-service
    ports:
      - "8004:8004"
    depends_on:
      - config-server
      - discovery-server
    networks:
      - microservices-net
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_APPLICATION_NAME: PaymentService
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/micro-service/protocol/openid-connect/certs
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/micro-service
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true" # Sử dụng IP thay vì hostname
      EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS: 10
      EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS: 30
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  notification-service:
    build: ./NotificationService
    container_name: notification-service
    ports:
      - "8005:8005"
    depends_on:
      - config-server
      - discovery-server
    networks:
      - microservices-net
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_APPLICATION_NAME: NotificationService
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/micro-service/protocol/openid-connect/certs
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/micro-service
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true" # Sử dụng IP thay vì hostname
      EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS: 10
      EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS: 30

  report-service:
    build: ./ReportService
    container_name: report-service
    ports:
      - "8007:8007"
    depends_on:
      - config-server
      - discovery-server
    networks:
      - microservices-net
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_APPLICATION_NAME: ReportService
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/micro-service/protocol/openid-connect/certs
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/micro-service
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true" # Sử dụng IP thay vì hostname
      EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS: 10
      EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS: 30

  recommend-service:
    build:
      context: ./RecommendService
    container_name: recommend-service
    ports:
      - "8008:8008"
    networks:
      - microservices-net
    depends_on:
      - config-server
    environment:
      - PINECONE_API_KEY=pcsk_6ngBzM_5ueoEuEehZZXiQZGiFJDWaAavcMizu9qSesb4uroh9hdykvYPfXCxFR7HVuSp69
      - PINECONE_ENV=us-east-1
      - PINECONE_INDEX=badminton
      - NESTJS_MENU_ENDPOINT=http://localhost:8222/products/products/all-no-paginate
      - JINA_API_TOKEN=jina_a3af64c8f3de45e3af0b040ba8d697ef-zZHaVUTWHLhl6E0QkRjm3a5kb4O

  behavior-service:
    build: ./UserBehaviorService
    container_name: behavior-service
    ports:
      - "8009:8009"
    depends_on:
      - config-server
      - discovery-server
    networks:
      - microservices-net
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_APPLICATION_NAME: UserBehaviorService
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/micro-service/protocol/openid-connect/certs
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/micro-service
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true" # Sử dụng IP thay vì hostname
      EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS: 10
      EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS: 30

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - microservices-net

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: ms_kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    networks:
      - microservices-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - xpack.monitoring.templates.enabled=true
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --silent --fail http://localhost:9200/_cluster/health || exit 1",
        ]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - microservices-net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.3
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    networks:
      - microservices-net

  logstash:
    image: docker.elastic.co/logstash/logstash:8.17.3
    container_name: logstash
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5000:5000" # Nhận logs từ Microservices qua TCP
      - "9600:9600" # Cổng quản lý Logstash
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - microservices-net

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    volumes:
      - zipkin-data:/zipkin-data
    ports:
      - "9411:9411"
    networks:
      - microservices-net

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.2
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: h2
      # KC_HOSTNAME: keycloak
    volumes:
      - keycloak-h2-data:/opt/keycloak/data
    ports:
      - "9098:8080"
    networks:
      - microservices-net
    #    command:
    #      - "start-dev"
    command:
      - "start-dev"
      - --hostname-strict=false
      - --hostname-url=http://keycloak:8080

volumes:
  keycloak-h2-data:
  zipkin-data:
  es_data:

networks:
  microservices-net:
    driver: bridge
