spring:
  datasource:
    url: jdbc:mysql://paymentservice-htbphuong10591-9ca8.h.aivencloud.com:22096/paymentservice?sslMode=REQUIRED
    username: avnadmin
    password: AVNS_t9N6gnba921vbvTe8yt
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:9098/realms/micro-service
          jwk-set-uri: http://keycloak:9098/realms/micro-service/protocol/openid-connect/certs

  kafka:
    producer:
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: paymentResponse:com.example.paymentservice.modules.payments.dto.PaymentResponse

    consumer:
      bootstrap-servers: kafka:9092
      group-id: orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: orderResponse:com.example.paymentservice.modules.feign.OrderResponse

server:
  port: 8004

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers,prometheus


