spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/productservice?sslMode=REQUIRED}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/micro-service
          jwk-set-uri: http://keycloak:8080/realms/micro-service/protocol/openid-connect/certs

server:
  port: 8002

cloudinary:
  cloud-name: daxxuqogj
  api-key: 436316462347214
  api-secret: 5oIMlaDECvys_-OGGZt-Irk8_Hw