spring:
  datasource:
    url: jdbc:mysql://notificationservice-uyenngungbp10591-536f.h.aivencloud.com:22412/reportservice?sslMode=REQUIRED
    username: avnadmin
    password: AVNS_pZtveC7EykeIERXc1Ab
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8007