spring:
  datasource:
    url: jdbc:mysql://paymentservice-haruki10591-7ac1.h.aivencloud.com:27675/behaviorservice?sslMode=REQUIRED
    username: avnadmin
    password: AVNS_4OULqQlI7UPul425sAn
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://keycloak:8080/realms/micro-service"
          jwk-set-uri: http://keycloak:8080/realms/micro-service/protocol/openid-connect/certs

server:
  port: 8009


