server:
  port: 8222

spring:

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/micro-service
          jwk-set-uri: http://keycloak:8080/realms/micro-service/protocol/openid-connect/certs
  config:
    import: optional:configserver:http://config-server:8888
  application:
    name: GatewayService
  data:
    cache:
      type: redis
    redis:
      host: redis
      port: 6379
      timeout: 5000
  cloud:
    gateway:
      default-filters:
        - name: RequestRateLimiter
          args:
            key-resolver: "#{@ipKeyResolver}"
            redis-rate-limiter.replenishRate: 50
            redis-rate-limiter.burstCapacity: 50
            redis-rate-limiter.requestedTokens: 50
      forwarded:
        enabled: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: UserService
          uri: lb:http://USERSERVICE
          predicates:
            - Path=/users/**
        - id: ProductService
          uri: lb:http://PRODUCTSERVICE
          predicates:
            - Path=/products/**
        - id: OrderService
          uri: lb:http://ORDERSERVICE
          predicates:
            - Path=/orders/**
        - id: PaymentService
          uri: lb:http://PAYMENTSERVICE
          predicates:
            - Path=/payment/**
        - id: NotificationService
          uri: lb:http://NOTIFICATIONSERVICE
          predicates:
            - Path=/notifications/**
        - id: ReportService
          uri: lb:ws://REPORTSERVICE
          predicates:
            - Path=/ws/**
        - id: UserBehaviorService
          uri: lb:http://USERBEHAVIORSERVICE
          predicates:
            - Path=/behaviors/**
        - id: RecommendService
          uri: http://recommend-service:8008
          predicates:
            - Path=/recommend/**

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

logging:
  level:
    root: DEBUG
    org.springframework.security: DEBUG
    com.example.gateway.security: DEBUG

bucket4j:
  enabled: true
  filters:
    - cache-name: buckets
      url: .*
      http-status-code: 429
      rate-limits:
        - bandwidths:
            - capacity: 50
              time: 1
              unit: minutes
      strategy: first
      filter-method: webflux
  scope: ip
