spring:
  application:
    name: ReportService
  config:
    import: optional:configserver:http://config-server:8888
  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 10 # Số lần retry tối đa
        initial-interval: 2000 # Thời gian chờ trước lần retry đầu tiên (ms)
        multiplier: 1.5 # Hệ số nhân giữa các lần retry
        max-interval: 10000

application:
  config:
    user-url: http://gateway:8222/users/

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

fcm:
  api:
    url: https://fcm.googleapis.com/fcm/send