spring:
    application:
        name: UserService
    config:
        import: optional:configserver:http://localhost:8888

logging:
    level:
        root: INFO
    appender:
        logstash:
            destination: logstash:5000