spring:
  application:
    name: OrderService
  config:
    import: optional:configserver:http://config-server:8888

  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 10 # Số lần retry tối đa
        initial-interval: 2000 # Thời gian chờ trước lần retry đầu tiên (ms)
        multiplier: 1.5 # Hệ số nhân giữa các lần retry
        max-interval: 10000

  kafka:
    producer:
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderResponse:com.example.orderservice.modules.Orders.dto.OrderResponse

    consumer:
      bootstrap-servers: kafka:9092
      group-id: paymentGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: paymentResponse:com.example.orderservice.modules.feign.Payments.PaymentResponse

logging:
  level:
    root: INFO
  appender:
    logstash:
      destination: logstash:5000

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

application:
  config:
    user-url: http://gateway:8222/users/users
    product-url: http://gateway:8222/products/products
